# PyGeM

## Tutorial 2: Free Form Deformation on a cylinder in CAD file format

In this tutorial we show again an application of _free form deformation_ method, now to a CAD file. These files, that are often adopted to model complex geometries, require an additional pre- and post-processing of the surfaces to perform the deformation.

The **CAD** submodule of **PyGeM** takes care of the deformation to all CAD files (.step, .iges, etc.), so first of all we import from the submodule the `FFD` class.

In [ ]:
import sys
import platform

print(f"Python Version: {sys.version}")
print(f"Platform: {sys.platform}")
print(f"System: {platform.system()} {platform.release()}")

try:
    import pygem

    print(f"PyGeM version: {pygem.__version__}")
except ImportError:
    print("PyGeM not found. Installing...")
    import subprocess

    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-e", ".[tut]"]
    )
    import pygem

    print(f"PyGeM version: {pygem.__version__}")

import numpy as np

np.random.seed(42)
from pygem.cad import FFD

Python Version: 3.9.25 (main, Nov  3 2025, 22:33:05) 
[GCC 11.2.0]
Platform: linux
System: Linux 6.12.0-55.41.1.el10_0.x86_64


PyGeM version: 2.0.0


Since the visualisation of CAD files may be tricky (depending by the operating system, the graphical front-end, ...), we avoid for this tutorial any graphical renderer, letting to the reader the possibility to implement by himself the needed plotting routines.

The `FFD` class in the **CAD** module shares the same interface with the original `FFD` class (for discrete geometries). We can simply parse a parameter file to set everything like we want (remember you can do the same directly setting the object attributes).

In [2]:
ffd = FFD()
import os

# Get absolute path to project root
project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))

ffd.read_parameters(
    os.path.join(
        os.path.join(
            project_root,
            "tests",
            "test_datasets",
            "parameters_test_ffd_iges.prm",
        )
    )
)

print(ffd)

conversion_unit = 1.0
n_control_points = [2 2 2]

box_length = [2200. 2200. 5100.]
box_origin = [-1100. -1100.  5000.]
rot_angle  = [0. 0. 0.]

array_mu_x =
[[[0.  0. ]
  [0.  0. ]]

 [[0.  0. ]
  [0.  0.3]]]

array_mu_y =
[[[0.  0. ]
  [0.  0. ]]

 [[0.  0. ]
  [0.  0.4]]]

array_mu_z =
[[[0.  0.5]
  [0.  0.5]]

 [[0.  0.2]
  [0.  0.2]]]

rotation_matrix = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

position_vertices = [[-1100. -1100.  5000.]
 [ 1100. -1100.  5000.]
 [-1100.  1100.  5000.]
 [-1100. -1100. 10100.]]



Almost already completed! We now specify the input file (the one which contains the shape to deform) and the output file: these are the two input argument to pass to the object in order to perform the deformation.

In [3]:
input_cad_file_name = os.path.join(
    project_root, "tests", "test_datasets", "test_pipe.iges"
)
modified_cad_file_name = "test_pipe_deformed.iges"
ffd(input_cad_file_name, modified_cad_file_name)

Total number of loaded entities 49.



/mnt/raid/kpandey/Kshitij/ITCS/PyGeM/pygem/cad/cad_deformation.py:201: DeprecationWarning: Call to deprecated function geomconvert_SurfaceToBSplineSurface since pythonocc-core 7.7.1. This function will be removed in a future release, please rather use the static method geomconvert.SurfaceToBSplineSurface
  bspline_surface = geomconvert_SurfaceToBSplineSurface(surface)
/mnt/raid/kpandey/Kshitij/ITCS/PyGeM/pygem/cad/cad_deformation.py:236: DeprecationWarning: Call to deprecated function BRep_Tool_Curve since pythonocc-core 7.7.1. This function will be removed in a future release, please rather use the static method BRep_Tool.Curve
  nurbs_curve = BRep_Tool_Curve(nurbs_edge)[0]
/mnt/raid/kpandey/Kshitij/ITCS/PyGeM/pygem/cad/cad_deformation.py:239: DeprecationWarning: Call to deprecated function geomconvert_CurveToBSplineCurve since pythonocc-core 7.7.1. This function will be removed in a future release, please rather use the static method geomconvert.CurveToBSplineCurve
  bspline_curve = 

The output file is created and the deformed shape is stored into it. We skip any visual check because of the **CAD** format file, so as final proof we simply show the differences, lines by lines, between the input and the output. Even if we can't be sure about the correctness of the results, in this way we ensure the outcome is different from the original inpuit.

In [4]:
!diff -y ../tests/test_datasets/test_pipe.iges test_pipe_deformed.iges

diff: ../tests/test_datasets/test_pipe.iges: No such file or directory
