# PyGeM

## Tutorial 2: Free Form Deformation on a cylinder in CAD file format

In this tutorial we show again an application of _free form deformation_ method, now to a CAD file. These files, that are often adopted to model complex geometries, require an additional pre- and post-processing of the surfaces to perform the deformation.

The **CAD** submodule of **PyGeM** takes care of the deformation to all CAD files (.step, .iges, etc.), so first of all we import from the submodule the `FFD` class.

In [1]:
import platform
import sys
import logging
import numpy as np

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)


# System info
logging.info(f"Python Version: {sys.version}")
logging.info(f"Platform: {sys.platform}")
logging.info(f"System: {platform.system()} {platform.release()}")

# Import PyGeM
try:
    import pygem
except ImportError:
    raise ImportError(
        "PyGeM not found. Please install it before running this tutorial.\n"
        "For example, run: pip install -e '.[tut]' in your environment."
    )

logging.info(f"PyGeM version: {pygem.__version__}")

np.random.seed(42)
from pygem.cad import FFD

2025-11-26 22:09:12,578 - INFO - Python Version: 3.9.25 (main, Nov  3 2025, 22:33:05) 
[GCC 11.2.0]


2025-11-26 22:09:12,579 - INFO - Platform: linux


2025-11-26 22:09:12,579 - INFO - System: Linux 6.12.0-55.41.1.el10_0.x86_64


2025-11-26 22:09:13,021 - INFO - PyGeM version: 2.0.0


Since the visualisation of CAD files may be tricky (depending by the operating system, the graphical front-end, ...), we avoid for this tutorial any graphical renderer, letting to the reader the possibility to implement by himself the needed plotting routines.

The `FFD` class in the **CAD** module shares the same interface with the original `FFD` class (for discrete geometries). We can simply parse a parameter file to set everything like we want (remember you can do the same directly setting the object attributes).

In [2]:
ffd = FFD()
import os

# Get absolute path to project root
project_root = os.path.abspath(os.path.join(os.getcwd(), "..", ".."))

ffd.read_parameters(
    os.path.join(
        os.path.join(
            project_root,
            "tests",
            "test_datasets",
            "parameters_test_ffd_iges.prm",
        )
    )
)

print(ffd)

conversion_unit = 1.0
n_control_points = [2 2 2]

box_length = [2200. 2200. 5100.]
box_origin = [-1100. -1100.  5000.]
rot_angle  = [0. 0. 0.]

array_mu_x =
[[[0.  0. ]
  [0.  0. ]]

 [[0.  0. ]
  [0.  0.3]]]

array_mu_y =
[[[0.  0. ]
  [0.  0. ]]

 [[0.  0. ]
  [0.  0.4]]]

array_mu_z =
[[[0.  0.5]
  [0.  0.5]]

 [[0.  0.2]
  [0.  0.2]]]

rotation_matrix = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

position_vertices = [[-1100. -1100.  5000.]
 [ 1100. -1100.  5000.]
 [-1100.  1100.  5000.]
 [-1100. -1100. 10100.]]



Almost already completed! We now specify the input file (the one which contains the shape to deform) and the output file: these are the two input argument to pass to the object in order to perform the deformation.

In [3]:
input_cad_file_name = os.path.join(
    project_root, "tests", "test_datasets", "test_pipe.iges"
)
modified_cad_file_name = "test_pipe_deformed.iges"
ffd(input_cad_file_name, modified_cad_file_name)

The output file is created and the deformed shape is stored into it. We skip any visual check because of the **CAD** format file, so as final proof we simply show the differences, lines by lines, between the input and the output. Even if we can't be sure about the correctness of the results, in this way we ensure the outcome is different from the original inpuit.

In [4]:
!diff -y ../tests/test_datasets/test_pipe.iges test_pipe_deformed.iges

diff: ../tests/test_datasets/test_pipe.iges: No such file or directory
